name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # It's important to use a token with write permissions to push changes.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'sahilpanhotra'
          git config --global user.email 'sahilpanhotra@gmail.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/makerkit/documentation

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          # Ensure we are on the main branch
          git checkout main 
          git merge upstream/main --no-edit 

      - name: Push Changes to Fork
        run: git push origin main